### ISSUE TITLE
Error caused by negative pavement life

### ISSUE THREAD

**Issue by sanet1313** [fritzjoostenz/cassandra_default_road_model#3]
Hi Dean
Below is the workflow that caused the infinity error in init_flush_proba:
![image](https://github.com/user-attachments/assets/723555e6-0b12-4eab-b51b-67402ce54d06)

Explanation:
1.	I start off with a pavement date that is less than one year from the current date in the template so that my pavement age is 0.69
2.	The pavement remaining life from my input file is -1
3.	This causes the initial pavement life to be 0.69 + (-1) = -0.31
4.	Initial pavement life achieved then becomes (0.69/-0.31)*100 = -0.00214
5.	This causes initial HCV risk factor b to be the root of a negative number which causes the error. 
6.	Initial flushing probability is a function of the HCV risk and therefore causes an error.

Below is the error received from Casandra
![image](https://github.com/user-attachments/assets/692746b6-d76c-4aba-8416-7813218cdb81)

**Comment by Potholer15** [comment]
There is a tricky choice to solve this issue. On one hand it is a valid error; the pavement life is negative, which means the input data needs to be checked (even a very light pavement renewal should have more than 10 years life expectancy). On the other hand, a fall through value will allow the model to run, but the operator will not be aware there is an error in the input data. I think the best outcome is to have a specific error message. I will set up a function that will induce an error message to point the operator at the input data problem.

**Comment by fritzjoostenz** [comment]
Noted. Happy to go with an informative error. Do you want me to add a JFunction that throws an error? Format would be something like: [if A = B : (error message here)]. For example:
n: input_error = 0 : pavement remaining life cannot be XXX

**Comment by Potholer15** [comment]
Yes, that would be awesome

**Comment by fritzjoostenz** [comment]
OK I will do it today and release an upgrade either today or tomorrow. So just hold fast on this one for a day or two

**Comment by Potholer15** [comment]
Thanks Fritz, I have updated in my working copy and will commit to github
