### ISSUE TITLE
Relax the conditions to satisfy holding actions on AC surfacing. 

### ISSUE THREAD

**Issue by sanet1313** [fritzjoostenz/cassandra_default_road_model#4]
We need to take the ac_ok_flag out of the holding ac treatment, otherwise an ac will never be allowed when the pavement is not strong enough. We need to allow for the opportunity to do heavy repairs to get the pavement ok for ac without forcing it towards a rehab_ac. 

Suggest the following solution:
In the image below:

![image](https://github.com/user-attachments/assets/a992cdc8-3a83-4b5e-9974-68c14ca78a93)
In the second line remove the last part out of the equation after the AND, i.e. remover this: "AND n : renw_ac_ok_flag = 1"

**Comment by Potholer15** [comment]
Will updated
