### ISSUE TITLE
Add 'first_treatment_year' column and logic for fine-tuning 3 year FWP

### ISSUE THREAD

**Issue by fritzjoostenz** [fritzjoostenz/cassandra_default_road_model#8]
We found for the Local Authorities there are sometimes access and low volume roads in bad condition - they need treatment at some stage but because of low traffic, the client wants to kick the can down the road for a few years.
We solved this by adding a column to the input file in which we can set the first year to consider for treatment. This becomes a parameter, e.g. 'par_first_treat_period' which we can set to say 3 in the input file for certain roads. **It is a sort of manual fine-tuning to certain roads down the priotity list without having to add a spaghetti set of additional trigger rules**.

In the candidate selection block, we then use the model period and compare to the first allowed treatment period - that way we can remove an element from consideration until say year 3. We implemented this in our Nelson model and it works fine. So if you can duplicate this concept in the general model that would be great.

**Comment by Potholer15** [comment]
Will add. But don't like to encourage kicking the can. Next update will be end of week. I will give you a call on Friday for wrap up and presentation, maybe we do a Teams.

**Comment by Potholer15** [comment]
Updated my working model, will commit to github
